# Generated by Django 6.0 on 2026-08-21 08:06

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("content", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="studyplan",
            name="is_completed",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="resource",
            name="resource_type",
            field=models.CharField(
                choices=[
                    ("video", "Video"),
                    ("article", "Article"),
                    ("ai_note", "AI Note"),
                ],
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="resource",
            name="url",
            field=models.URLField(blank=True, null=True),
        ),
    ]
