# Generated by Django 6.0 on 2026-08-25 11:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "content",
            "0002_studyplan_is_completed_alter_resource_resource_type_and_more",
        ),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="resource",
            name="resource_type",
            field=models.CharField(
                choices=[
                    ("video", "Video"),
                    ("article", "Article"),
                    ("ai_note", "AI Note"),
                    ("user_note", "User Note"),
                ],
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="resource",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="resources",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
