# Generated by Django 5.1.5 on 2026-09-02 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0003_alter_resource_resource_type_alter_resource_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resource',
            name='resource_type',
            field=models.CharField(choices=[('video', 'Video'), ('article', 'Article'), ('ai_note', 'AI Note'), ('user_note', 'User Note'), ('step_note', 'Step Note')], max_length=20),
        ),
    ]
