# Generated by Django 6.0 on 2025-12-07 19:31

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("user", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="userprofile",
            name="daily_focus",
            field=models.IntegerField(default=0, help_text="Minutes focused today"),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="focus_history",
            field=models.JSONField(
                default=list,
                help_text="List of daily focus minutes for the last 7 days",
            ),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="weekly_goal",
            field=models.IntegerField(default=10, help_text="Weekly goal in hours"),
        ),
    ]
