# Generated by Django 6.0 on 2026-08-20 14:49

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("user", "0002_userprofile_daily_focus_userprofile_focus_history_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="userprofile",
            name="daily_focus",
        ),
        migrations.RemoveField(
            model_name="userprofile",
            name="interests",
        ),
        migrations.RemoveField(
            model_name="userprofile",
            name="level",
        ),
        migrations.RemoveField(
            model_name="userprofile",
            name="xp",
        ),
        migrations.AlterField(
            model_name="userprofile",
            name="focus_history",
            field=models.JSONField(
                default=dict,
                help_text="Map of date string to focus seconds for the last 7 days",
            ),
        ),
    ]
