# Generated by Django 6.0 on 2026-08-21 08:49

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("user", "0003_remove_userprofile_daily_focus_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="userprofile",
            name="avatar",
            field=models.ImageField(blank=True, null=True, upload_to="avatars/"),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="display_name",
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
