# Generated by Django 5.1.5 on 2026-09-01 06:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_audit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='audit',
            name='source',
            field=models.CharField(choices=[('ai_tutor', 'AI Tutor'), ('study_plan', 'Study Plan'), ('study_step', 'Study Step'), ('unknown', 'Unknown')], default='unknown', max_length=20),
        ),
    ]
